# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - "**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Check the source code

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KE }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_DEV_URI: ${{ secrets.REACT_APP_DEV_URI }}
      REACT_APP_PRO_URI: ${{ secrets.REACT_APP_PRO_URI }}
      REACT_APP_TEST_URI: ${{ secrets.REACT_APP_TEST_URI }}
      REACT_APP_MICROCMS_URI_V1: ${{secrets.REACT_APP_MICROCMS_URI_V1 }}
      REACT_APP_MICROCMS_API_KEY: ${{secrets.REACT_APP_MICROCMS_API_KEY}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.11.0"
      - name: Install Packages
        run: yarn install
      - name: prettier format check
        run: yarn format
      - name: eslint review
        run: yarn lint
      - name: jest test
        run: yarn test
